name: edunotif
description: A minimalist school planner & notifier for students.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.0
  intl: ^0.19.0

  # State & Storage
  provider: ^6.1.2
  shared_preferences: ^2.3.0

  # Notifications + Timezone (REQUIRED for sound + scheduling)
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # Backend
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
